package navigation.administration.employeesNav;

import componentsFood.employee;
import util.buttonFormatters.iNavigatorButton;
import util.buttonFormatters.navigatorButtonFormatter;
import util.databaseAPIs.employeesAPI;
import util.databaseAPIs.rolesAPI;

import java.util.ArrayList;
import javax.swing.table.*;
import javax.swing.*;
import java.awt.*;

import java.awt.event.*;

public class mainEmployees {

    private JLabel clickEmployee = new JLabel("Double-Click on employee to edit it");
    private JButton addEmployeeButton = new JButton();
    private JTable myTable = new JTable();
    private JScrollPane employeesJScrollPanel = new JScrollPane(myTable, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
            JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    private DefaultTableModel model;

    public mainEmployees(JPanel panel3) {
        initPanel3(panel3);
        populateTable();
        addListeners(panel3);
    }

    private void initPanel3(JPanel panel3) {
        // This code was originally generated by Apache NetBeans.

        panel3.setBackground(new Color(255, 255, 255));
        clickEmployee.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        clickEmployee.setHorizontalAlignment(SwingConstants.CENTER);
        clickEmployee.setVerticalAlignment(SwingConstants.BOTTOM);

        GroupLayout panel3Layout = new GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
                panel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(employeesJScrollPanel, GroupLayout.PREFERRED_SIZE, 694,
                                        GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88))
                        .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout
                                        .createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(88, 88, 88)
                                                .addComponent(clickEmployee, GroupLayout.PREFERRED_SIZE,
                                                        707,
                                                        GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(334, 334, 334)
                                                .addComponent(addEmployeeButton, GroupLayout.PREFERRED_SIZE,
                                                        200, GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(75, Short.MAX_VALUE)));
        panel3Layout.setVerticalGroup(
                panel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(clickEmployee, GroupLayout.PREFERRED_SIZE, 35,
                                        GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(employeesJScrollPanel, GroupLayout.PREFERRED_SIZE, 337,
                                        GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addEmployeeButton, GroupLayout.PREFERRED_SIZE, 55,
                                        GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(97, Short.MAX_VALUE)));
    }

    private void addListeners(JPanel panel3) {

        // Detects which entry of the JTable has been clicked, and redirects to
        // "editEmployee" to edit it.
        myTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    try {
                        if (myTable.getValueAt(myTable.getSelectedRow(), 0).toString().equals(""))
                            return;

                        int ID = Integer.parseInt((String) model.getValueAt(myTable.getSelectedRow(), 0));
                        panel3.removeAll();
                        new editEmployee(panel3, employeesAPI.getEmployee(ID));
                        panel3.revalidate();
                        panel3.repaint();
                    } catch (IndexOutOfBoundsException e) {
                        return;
                    }
                }
            }
        });
        // Call to the method(s) which format each JButton / JTextField accordingly.
        addButton(panel3);
    }

    private void addButton(JPanel panel3) {
        class addMethodHolder extends iNavigatorButton {
            public void createNewNavigator() {
                new addEmployee(panel3);
            }
        }
        navigatorButtonFormatter.formatNavigationButton(addEmployeeButton, new addMethodHolder(), panel3, false,
                "Add Employee");
    }

    private void populateTable() {
        ArrayList<employee> tempList = employeesAPI.getAllCurrentEmployees();
        model = new DefaultTableModel(new String[] { "employee_id", "Name", "Salary", "Hours / Week", "Role" }, 0);
        for (employee temp : tempList) {
            String id = Integer.toString(temp.getId());
            String name = temp.getName();
            String salary = Float.toString(temp.getSalary());
            String hoursWeek = temp.getHoursWeek().substring(0, 5);
            String role = rolesAPI.getNameOfRole(temp.getRoleID());
            model.addRow(new String[] { id, name, salary, hoursWeek, role });
        }
        myTable.setDefaultEditor(Object.class, null);
        myTable.setFocusable(true);
        myTable.setModel(model);
        myTable.removeColumn(myTable.getColumn("employee_id"));
        myTable.getTableHeader().setFont(new Font("Segoe UI", 1, 14));
        myTable.getTableHeader().setBackground(new Color(120, 168, 252));
        myTable.setFillsViewportHeight(true);
        employeesJScrollPanel.getViewport().setBackground(new Color(245, 245, 245));
        employeesJScrollPanel.setBackground(new Color(245, 245, 245));
        myTable.setFont(new Font("Segoe UI", 0, 14));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        myTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        myTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Dimension temp = new Dimension(20, 1);
        myTable.setIntercellSpacing(temp);
        myTable.setRowHeight(myTable.getRowHeight() + 10);
    }
}