package navigation.home.items;

import java.awt.Font;
import java.awt.Color;
import java.awt.Dimension;

import java.util.ArrayList;

import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JToggleButton;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import componentsFood.menu;
import componentsFood.product;
import util.buttonFormatters.dashToggleFormatter;
import util.buttonFormatters.iDashToggleFormatter;
import util.databaseAPIs.categoryAPI;
import util.databaseAPIs.menuAPI;
import util.databaseAPIs.productAPI;

import java.awt.event.*;

public class mainItems {

    private JLabel infoLabel = new JLabel();
    private JTable itemsTable = new JTable();
    private JScrollPane itemJScrollPane = new JScrollPane(itemsTable, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
            JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
    private DefaultTableModel model;
    private JToggleButton sortButton = new JToggleButton();
    private JToggleButton swapButton = new JToggleButton();

    public mainItems(JFrame theFrame, JPanel panel3) {
        initPanel3(panel3);
        addListeners(theFrame, panel3);
    }

    private void initPanel3(JPanel panel3) {
        // This code was originally generated by Apache NetBeans.

        panel3.setBackground(new Color(255, 255, 255));

        setTableMenus(true);
        itemsTable.setRowHeight(itemsTable.getRowHeight() + 10);
        itemJScrollPane.revalidate();
        itemJScrollPane.repaint();

        infoLabel.setFont(new Font("Segoe UI", 0, 18)); // NOI18N
        infoLabel.setForeground(new Color(23, 35, 51));
        infoLabel.setText("Double-Click on an Item to edit its preview");

        javax.swing.GroupLayout panel3Layout = new GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
                panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel3Layout.createSequentialGroup()
                                .addGroup(panel3Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(331, 331, 331)
                                                .addComponent(swapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panel3Layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addGroup(panel3Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panel3Layout.createSequentialGroup()
                                                                .addComponent(infoLabel,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 387,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(176, 176, 176)
                                                                .addComponent(sortButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 137,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(itemJScrollPane,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 700,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(85, Short.MAX_VALUE)));
        panel3Layout.setVerticalGroup(
                panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel3Layout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addGroup(
                                        panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(sortButton)
                                                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(swapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)));
    }

    private void addListeners(JFrame theFrame, JPanel panel3) {
        itemsTable.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent me) {
                if (me.getClickCount() == 2) {
                    try {
                        itemsTable.getValueAt(itemsTable.getSelectedRow(), 0).toString().equals("");
                    } catch (IndexOutOfBoundsException e) {
                        return;
                    }
                    boolean isProduct = true;
                    if (swapButton.getText().equals("Swap to Products"))
                        isProduct = false;
                    int ID = Integer.parseInt((String) model.getValueAt(itemsTable.getSelectedRow(), 0));
                    String name = (String) model.getValueAt(itemsTable.getSelectedRow(), 1);
                    String category = (String) model.getValueAt(itemsTable.getSelectedRow(), 2);
                    int categoryID = categoryAPI.getCategoryID(category);
                    Float price = Float.parseFloat((String) model.getValueAt(itemsTable.getSelectedRow(), 3));
                    String date = (String) model.getValueAt(itemsTable.getSelectedRow(), 4);
                    panel3.removeAll();
                    if (isProduct) {
                        new editItems(theFrame, panel3, new product(ID, categoryID, date, name, price, true));
                    } else {
                        new editItems(theFrame, panel3, new menu(ID, categoryID, date, name, price, true));
                    }
                    panel3.revalidate();
                    panel3.repaint();
                }
            }
        });
        swapButton(panel3);
        sortButton(panel3);
    }

    private void sortButton(JPanel panel3) {
        class swapMethodHolder implements iDashToggleFormatter {
            public void action1() {
                if (swapButton.getText().equals("Swap to Products"))
                    setTableMenus(false);
                else
                    setTableProducts(false);
            }

            public void action2() {
                if (swapButton.getText().equals("Swap to Products"))
                    setTableMenus(true);
                else
                    setTableProducts(true);
            }
        }
        dashToggleFormatter.applyDashActionListenerToggle(sortButton, "Sort by Category", "Sort Alphabetically",
                new swapMethodHolder());
    }

    private void swapButton(JPanel panel3) {
        class swapMethodHolder implements iDashToggleFormatter {
            public void action1() {
                boolean alphabetical = false;
                if (sortButton.getText().equals("Sort by Category"))
                    alphabetical = true;
                setTableProducts(alphabetical);
            }

            public void action2() {
                boolean alphabetical = false;
                if (sortButton.getText().equals("Sort by Category"))
                    alphabetical = true;
                setTableMenus(alphabetical);
            }
        }
        dashToggleFormatter.applyDashActionListenerToggle(swapButton, "Swap to Products", "Swap to Menus",
                new swapMethodHolder());
    }

    private void setTableMenus(boolean isAlphabetical) {
        model = new DefaultTableModel(new String[] { "ID", "Name", "Category", "Price", "Date" }, 0);
        itemsTable.setModel(model);
        ArrayList<menu> menuList;
        if (isAlphabetical)
            menuList = menuAPI.getAllCurrentMenusAlphabetical();
        else
            menuList = menuAPI.getAllCurrentMenusByCategory();
        for (menu temp : menuList) {
            String ID = Integer.toString(temp.getId());
            String name = temp.getName();
            String category = categoryAPI.getNameOfCategory(temp.getCategoryID());
            String price = Float.toString(temp.getPrice());
            String date = temp.getDate();
            model.addRow(new String[] { ID, name, category, price, date });
        }
        setUpTable();
        itemJScrollPane.revalidate();
        itemJScrollPane.repaint();
    }

    private void setTableProducts(boolean isAlphabetical) {
        model = new DefaultTableModel(new String[] { "ID", "Name", "Category", "Price", "Date" }, 0);
        itemsTable.setModel(model);
        ArrayList<product> productList;
        if (isAlphabetical)
            productList = productAPI.getAllCurrentProductsAlphabetical();
        else
            productList = productAPI.getAllCurrentProductsByCategory();
        for (product temp : productList) {
            String ID = Integer.toString(temp.getId());
            String name = temp.getName();
            String category = categoryAPI.getNameOfCategory(temp.getCategoryID());
            String price = Float.toString(temp.getPrice());
            String date = temp.getDate();
            model.addRow(new String[] { ID, name, category, price, date });
        }
        setUpTable();
        itemJScrollPane.revalidate();
        itemJScrollPane.repaint();
    }

    private void setUpTable() {
        itemsTable.setDefaultEditor(Object.class, null);
        itemsTable.setFocusable(true);
        itemsTable.removeColumn(itemsTable.getColumn("ID"));
        itemsTable.removeColumn(itemsTable.getColumn("Date"));
        itemsTable.getTableHeader().setFont(new Font("Segoe UI", 1, 14));
        itemsTable.getTableHeader().setBackground(new Color(120, 168, 252));
        itemsTable.setFillsViewportHeight(true);
        itemsTable.setFont(new Font("Segoe UI", 0, 14));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        itemsTable.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        itemsTable.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        itemsTable.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Dimension tempdimen = new Dimension(20, 1);
        itemsTable.setIntercellSpacing(tempdimen);
    }

}